---
title: "Examples"
output:
  html_document: 
    theme: yeti
    toc: true
    toc_depth: 3
    toc_float: 
      collapsed: false
    
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(SVMMaj)
```

# SVMMaj

## Run model

```{r svmmaj simple}
X <- AusCredit.tr$X
y <- AusCredit.tr$y
model <- svmmaj(X, y, lambda = 100)
print(model)
summary(model)
```

## Plot model
```{r label='svmmaj simple plot', fig=TRUE, echo=FALSE}
plot(model)
```

## Predict model

```{r label='svmmaj predict', fig=TRUE}
Xnew <- AusCredit.te$X
ynew <- AusCredit.te$y
q <- predict(model, Xnew, show.plot = FALSE)
q <- predict(model, Xnew, show.plot = TRUE)
```

```{r label= 'svmmaj predict roccourve', fig=TRUE}
roccurve(q, ynew)
```

# svmmajcrossval 

## Run model
```{r label='svmmajcrossval simple'}
Xt <- diabetes$X
yt <- diabetes$y

## performing gridsearch with k-fold crossvalidation
results <- svmmajcrossval(
   Xt, yt, 
  scale = 'interval',
  mc.cores = 2,
  ngroup = 10,
  return.model = TRUE
)
print(results)
summary(results$model)
```

## Plot model

```{r label='svmmajcrossval plot', fig=TRUE}
plot(results)
plot(results, 'profile')
```

